//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.03 at 10:59:53 CEST 
//


package org.siri.feederconfig.xmlbinding;


/**
 * Java content class for errorType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/gepo/intellij_siri/modules/feeder/feederconfig/src/schema/feeder.xsd line 51)
 * <p>
 * <pre>
 * &lt;complexType name="errorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}errorfolderpath"/>
 *         &lt;element ref="{}errorinfofolderpath"/>
 *         &lt;element ref="{}sortonresend"/>
 *         &lt;element ref="{}CronJob"/>
 *         &lt;element name="errornotification" type="{}errornotificationType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="errorhandleron" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ErrorType {


    /**
     * Gets the value of the errornotification property.
     * 
     * @return
     *     possible object is
     *     {@link org.siri.feederconfig.xmlbinding.ErrornotificationType}
     */
    org.siri.feederconfig.xmlbinding.ErrornotificationType getErrornotification();

    /**
     * Sets the value of the errornotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.siri.feederconfig.xmlbinding.ErrornotificationType}
     */
    void setErrornotification(org.siri.feederconfig.xmlbinding.ErrornotificationType value);

    /**
     * Gets the value of the errorinfofolderpath property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getErrorinfofolderpath();

    /**
     * Sets the value of the errorinfofolderpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setErrorinfofolderpath(java.lang.String value);

    /**
     * Gets the value of the errorhandleron property.
     * 
     */
    boolean isErrorhandleron();

    /**
     * Sets the value of the errorhandleron property.
     * 
     */
    void setErrorhandleron(boolean value);

    /**
     * Gets the value of the sortonresend property.
     * 
     */
    boolean isSortonresend();

    /**
     * Sets the value of the sortonresend property.
     * 
     */
    void setSortonresend(boolean value);

    /**
     * Gets the value of the cronJob property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCronJob();

    /**
     * Sets the value of the cronJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCronJob(java.lang.String value);

    /**
     * Gets the value of the errorfolderpath property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getErrorfolderpath();

    /**
     * Sets the value of the errorfolderpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setErrorfolderpath(java.lang.String value);

}
