//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.03 at 10:59:53 CEST 
//


package org.siri.feederconfig.xmlbinding;


/**
 * Java content class for inactivityType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/gepo/intellij_siri/modules/feeder/feederconfig/src/schema/feeder.xsd line 42)
 * <p>
 * <pre>
 * &lt;complexType name="inactivityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}maxInactivityPeriodInMilliSeconds" minOccurs="0"/>
 *         &lt;element ref="{}emailOnInactivity" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="inactivityOn" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface InactivityType {


    /**
     * Gets the value of the inactivityOn property.
     * 
     */
    boolean isInactivityOn();

    /**
     * Sets the value of the inactivityOn property.
     * 
     */
    void setInactivityOn(boolean value);

    /**
     * Gets the value of the emailOnInactivity property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getEmailOnInactivity();

    /**
     * Sets the value of the emailOnInactivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setEmailOnInactivity(java.lang.String value);

    /**
     * Gets the value of the maxInactivityPeriodInMilliSeconds property.
     * 
     */
    long getMaxInactivityPeriodInMilliSeconds();

    /**
     * Sets the value of the maxInactivityPeriodInMilliSeconds property.
     * 
     */
    void setMaxInactivityPeriodInMilliSeconds(long value);

}
