//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.03 at 10:59:53 CEST 
//


package org.siri.feederconfig.xmlbinding;


/**
 * Java content class for infoldersendchunksType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/gepo/intellij_siri/modules/feeder/feederconfig/src/schema/feeder.xsd line 98)
 * <p>
 * <pre>
 * &lt;complexType name="infoldersendchunksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}infolderchunksize"/>
 *         &lt;element ref="{}infolderchunkthreshold"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sendinfolderchunkson" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface InfoldersendchunksType {


    /**
     * Gets the value of the infolderchunkthreshold property.
     * 
     */
    short getInfolderchunkthreshold();

    /**
     * Sets the value of the infolderchunkthreshold property.
     * 
     */
    void setInfolderchunkthreshold(short value);

    /**
     * Gets the value of the infolderchunksize property.
     * 
     */
    short getInfolderchunksize();

    /**
     * Sets the value of the infolderchunksize property.
     * 
     */
    void setInfolderchunksize(short value);

    /**
     * Gets the value of the sendinfolderchunkson property.
     * 
     */
    boolean isSendinfolderchunkson();

    /**
     * Sets the value of the sendinfolderchunkson property.
     * 
     */
    void setSendinfolderchunkson(boolean value);

}
