//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.03 at 10:59:53 CEST 
//


package org.siri.feederconfig.xmlbinding;


/**
 * Java content class for infolderchunkthreshold element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/gepo/intellij_siri/modules/feeder/feederconfig/src/schema/feeder.xsd line 96)
 * <p>
 * <pre>
 * &lt;element name="infolderchunkthreshold" type="{http://www.w3.org/2001/XMLSchema}short"/>
 * </pre>
 * 
 */
public interface Infolderchunkthreshold
    extends javax.xml.bind.Element
{


    /**
     * Gets the value of the value property.
     * 
     */
    short getValue();

    /**
     * Sets the value of the value property.
     * 
     */
    void setValue(short value);

}
