//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.03 at 10:59:53 CEST 
//


package org.siri.feederconfig.xmlbinding;


/**
 * Java content class for loggingType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/gepo/intellij_siri/modules/feeder/feederconfig/src/schema/feeder.xsd line 117)
 * <p>
 * <pre>
 * &lt;complexType name="loggingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="appender" type="{}appenderType"/>
 *         &lt;element ref="{}logpattern"/>
 *         &lt;element ref="{}logfolderpath"/>
 *         &lt;element ref="{}loglevel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface LoggingType {


    /**
     * Gets the value of the appender property.
     * 
     * @return
     *     possible object is
     *     {@link org.siri.feederconfig.xmlbinding.AppenderType}
     */
    org.siri.feederconfig.xmlbinding.AppenderType getAppender();

    /**
     * Sets the value of the appender property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.siri.feederconfig.xmlbinding.AppenderType}
     */
    void setAppender(org.siri.feederconfig.xmlbinding.AppenderType value);

    /**
     * Gets the value of the loglevel property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getLoglevel();

    /**
     * Sets the value of the loglevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setLoglevel(java.lang.String value);

    /**
     * Gets the value of the logpattern property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getLogpattern();

    /**
     * Sets the value of the logpattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setLogpattern(java.lang.String value);

    /**
     * Gets the value of the logfolderpath property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getLogfolderpath();

    /**
     * Sets the value of the logfolderpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setLogfolderpath(java.lang.String value);

}
